### ISSUE TITLE
ILS Cookie is not saved in some browsers

### ISSUE THREAD

**Issue by alextrichos** [react-epfl/gadget#146]
The cookie with the student name is not saved in some browsers like Safari and Firefox.
The fact that works on Chrome may indicate that there is some security issue preventing the browsers to accept the cookie. Maybe a '3rd party' cookie policy of some browsers ?

**Comment by MJRodriguezTriana** [comment]
This issue has been solved by using the local storage as an additional way to store the current user. See #244
