### ISSUE TITLE
Descriptions which contain speech marks stop ILS from loading

### ISSUE THREAD

**Issue by ajwild** [react-epfl/gadget#233]
The data passed from Go-Labs to Graasp for a space description is a string and not HTML (@sten is changing this to HTML now). When you try and open the standalone view it gets stuck on the loading screen and logs the following console error:
```
Uncaught Error: Syntax error, unrecognized expression: Welcome! "Bond" is integrated in the "Investigation" phase. Click and type here to edit this ...
```
This is due to how the code assumes the description is HTML. I think it would be good to handle both, in which case the following code (app.js line 126) needs to be updated from:
```
if (currentSpace.description && currentSpace.description.replace(/[\s|&nbsp;]+/gi,'') !="" && $(currentSpace.description).text()!=""){
```
to (when empty p tags can be added):
```
if (currentSpace.description && currentSpace.description.replace(/[\s|&nbsp;]+/gi,'') !== ""){
```
or (assuming the first character of "<" is HTML and not just text):
```
if (currentSpace.description && currentSpace.description.replace(/[\s|&nbsp;]+/gi,'') !== "" && (currentSpace.description.charAt(0) === "<" && $(currentSpace.description).text() !== "")){
```
Another more reliable option would be to bind it (even if the element isn't attached to the DOM) then check the content using jQuery.text().

**Comment by MJRodriguezTriana** [comment]
@ajwild this is not a problem anymore, is it? Can we close the issue?

**Comment by ajwild** [comment]
Resolved with new standalone view implementation.
