### ISSUE TITLE
ILS login page design 

### ISSUE THREAD

**Issue by aholzer** [react-epfl/gadget#242]
Update the login screen background, login box and go-lab logo

add a password box and a forgot password link (for now these features can be hidden, they will need to appear once we'll have the temporary users)

![screen shot 2015-01-19 at 13 51 00](https://cloud.githubusercontent.com/assets/2970525/5800697/6ab64018-9fe2-11e4-8d78-5611dad1aa34.png)

**Comment by alextrichos** [comment]
Are we aware of the desired dimensions of the new Golab logo (if you have the logo image please send the image itself) as well as the font sizes for the welcome text, input fields and forgot password link ?
If not I can try to match what I see ...

**Comment by aholzer** [comment]
Try to match what you see, basically the welcome, nickname and pwd the same size and the forgot password small.

the idea is to have these boxes quite big so that it looks a bit fun
