### ISSUE TITLE
Problem identified with the "Student time spent" widget

### ISSUE THREAD

**Issue by MJRodriguezTriana** [react-epfl/gadget#264]
Problem identified with the "Student time spent" widget:
![screen shot 2015-02-05 at 18 21 25](https://cloud.githubusercontent.com/assets/8037223/6065275/2b839a8c-ad64-11e4-9ceb-4d9965820b32.png)

**Comment by davidsandoz** [comment]
@MJRodriguezTriana Thanks for the heads up. It will be fixed with the with the version of the gadget implementing #250
