### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by ajwild** [react-epfl/gadget#273]
We need to add Google Analytics to the ILS standalone view. We will be adding this to the home page etc soon so you could copy the code from there, or ask @voz for more details. The code we need to use for Graasp is UA-60033764-1.

Is there a way you can check for AngeLA and only load the tracking script if the user is a member of the ILS?

**Comment by voz** [comment]
Here is the code we need to put:

```html
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-60033764-1', 'auto');
  ga('send', 'pageview');

</script>
```

@MJRodriguezTriana do you want me to do it or you will do it yourself?
