### ISSUE TITLE
ILS Design width margin improvement

### ISSUE THREAD

**Issue by aholzer** [react-epfl/gadget#280]
Increase the outside padding of the white space of the ILS standalone view from 10px to 100px. The content stays 940 (I think thats the new width), but the outside gets wider as shown in the image below

when the screen size gets smaller than the new width of the white space  (1140), the margin becomes smaller until it reaches the minimum of 10px, then the content becomes smaller.

![screen shot 2015-03-05 at 16 57 43](https://cloud.githubusercontent.com/assets/2970525/6508418/f3da8324-c358-11e4-9942-753ce141223c.png)

**Comment by aholzer** [comment]
@alextrichos actually start with 50px instead of 100px (basically 5% on each side)

**Comment by alextrichos** [comment]
@aholzer Have a look at an ILS using the Certh metawidget (.../metaWidgetType/ilsCERTH?lang=en). This is with a variable margin of a minimum 10px to max 50px.

**Comment by aholzer** [comment]
Cool!

one thing, the alignment of the first tab is a bit weird

I think it is nicer to align the text in the tab with the text and resources in the ILS, like in the current standalone view ()

Also, check the behavior with many tabs, it seems a bit off (check below)

cheers

—
adrian

[cid:5990F465-4F59-452E-833D-AAB2FC04F7A4]

[cid:0EF64862-BAD3-4824-8867-BBA99774EA2D]

[cid:11F141B9-CDE9-4606-BEC3-C0827570F21A]


On 9 mars 2015, at 13:16, alextrichos <notifications@github.com<mailto:notifications@github.com>> wrote:


@aholzer<https://github.com/aholzer> Have a look at an ILS using the Certh metawidget (.../metaWidgetType/ilsCERTH?lang=en). This is with a variable margin of a minimum 10px to max 50px.

**Comment by MJRodriguezTriana** [comment]
Already addressed by Alexandros
