### ISSUE TITLE
Time spent widget: show time selection menus in a user friendly way

### ISSUE THREAD

**Issue by MJRodriguezTriana** [react-epfl/gadget#302]
The way that we are showing the menu time definition to the user is not user friendly:

![screen shot 2015-06-03 at 18 14 29](https://cloud.githubusercontent.com/assets/8037223/7965314/e9b1a516-0a1c-11e5-9fc9-db6da6cfcfdb.png)
![screen shot 2015-06-03 at 18 14 52](https://cloud.githubusercontent.com/assets/8037223/7965316/eccf6ac6-0a1c-11e5-98ef-bb65fc3f88f7.png)

@voz @davidsandoz  Could we provide any other solution?

**Comment by davidsandoz** [comment]
@MJRodriguezTriana Well, it is not supposed to show time selection like that. Is it the same thing in every browser?

**Comment by MJRodriguezTriana** [comment]
@davidsandoz Yes, it's shown in the same way in Chrome, Firefox, Safari and Opera

**Comment by davidsandoz** [comment]
@MJRodriguezTriana Ok, weird. It was working fine when I introduced the new picker.
I will have a look, but I won't have time before the middle of next week.

**Comment by voz** [comment]
Maybe something with CSS? @MJRodriguezTriana dod you see any errors in the console?
